services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://bookly_user:bookly_pass@db:5432/bookly_db
      JWT_SECRET: supersecretjwtkey123
      JWT_ALGORITHM: HS256
      MAIL_USERNAME: berenice.macgyver12@ethereal.email
      MAIL_PASSWORD: PJHMa6WgMBbWXXPxet
      MAIL_SERVER: smtp.ethereal.email
      MAIL_PORT: 587
      MAIL_FROM: bookly@ethereal.email
      MAIL_FROM_NAME: Bookly
      DOMAIN: localhost:8000
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

    networks:
      - app-network

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: bookly_user
      POSTGRES_DB: bookly_db
      POSTGRES_PASSWORD: bookly_pass
    ports:
     - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network

  redis:
    image: redis:6

    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: .
    command: celery -A src.celery_tasks.c_app worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://bookly_user:bookly_pass@db:5432/bookly_db
      JWT_SECRET: supersecretjwtkey123
      JWT_ALGORITHM: HS256
      MAIL_USERNAME: berenice.macgyver12@ethereal.email
      MAIL_PASSWORD: PJHMa6WgMBbWXXPxet
      MAIL_SERVER: smtp.ethereal.email
      MAIL_PORT: 587
      MAIL_FROM: bookly@ethereal.email
      MAIL_FROM_NAME: Bookly
      DOMAIN: localhost:8000
      REDIS_URL: redis://redis:6379/0
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge